Changes in service ..
CarlosFabianG/beer-inventory pull request #18
Opened 2021-02-17 01:41 UTC by mayralgr

#7 
#9

2021-02-19 03:45 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/mappers/BeerMapping.java
> +import java.util.Optional;
Donde estas utilizando el Optional?

2021-02-19 03:47 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/controller/BeerController.java
>      @PostMapping("/")
No debería ser GET? Para obtener UNA cerveza por su ID

2021-02-19 03:49 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/controller/BeerController.java
> +import com.academy.beerinventory.mappers.BeerMapping;
No se necesita en el controller

2021-02-19 03:49 UTC, mayralgr commented on src/main/java/com/academy/beerinventory/web/controller/BeerController.java
>      @PostMapping("/")
ops, lo corrijo asap

2021-02-19 03:53 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/BeerServiceImpl.java
> +        BeerDto beerDto = BeerMapping.BeerToBeerDto(beer.orElse(null));
Captura lo que regresa beer.orElseThrow en una variable y esa variable la metes en el mapper

2021-02-19 03:54 UTC, mayralgr commented on src/main/java/com/academy/beerinventory/web/service/BeerServiceImpl.java
> +        BeerDto beerDto = BeerMapping.BeerToBeerDto(beer.orElse(null));
pero a ti no te gustan las buenas practicas

2021-02-19 03:57 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/BeerServiceImpl.java
> +    public BeerDto addBeer(Beer beer) {
Debes de pedir como parámetro una BeerDto y convertirla en el servicio con el mapper a Beer y guardarla

2021-02-19 03:58 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/BeerServiceImpl.java
> +    public BeerDto updateBeer(long id, Beer beer) {
The same that above

2021-02-19 03:59 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/IBeerService.java
> +    public BeerDto addBeer(Beer beer);
Lo mismo los parámetros que tomas en addBeer and updateBeer tienen que ser BeerDto(que es lo que te manda el user) y convertirlo en el servicio a Beer para guardarlo/actualizarlo en BBDD

2021-02-19 04:00 UTC, OmarMorales71 requested changes
Revisa los comentarios, Java>JS

2021-02-19 04:00 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/IBeerService.java
> +    public BeerDto updateBeer(long id, Beer beer);
Wuen trabajo! Saludos desde la playita

2021-02-19 04:03 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/service/BeerServiceImpl.java
> +        BeerDto beerDto = BeerMapping.BeerToBeerDto(beer.orElse(null));
JAJAJA pero lo que te digo es buena practica, estoy evitando que hagas dos veces .orElse...

2021-02-23 18:57 UTC, mayralgr commented
> Revisa los comentarios, Java>JS
por favor ubicate

2021-02-23 19:38 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/controller/BeerController.java
> +    @GetMapping("/")
Get mapping de una cerveza debe de pedir el id por la url /{beerId} y 
```suggestion
    @GetMapping("/{beerId}")
```

2021-02-23 19:39 UTC, OmarMorales71 commented on src/main/java/com/academy/beerinventory/web/controller/BeerController.java
>      public ResponseEntity<BeerDto> getBeer(Long id){
```suggestion
    public ResponseEntity<BeerDto> getBeer(@PathVariable Long beerId){
```

2021-02-23 19:41 UTC, OmarMorales71 requested changes
LGTM

2021-02-23 19:42 UTC, merged